### ISSUE TITLE
Using Base64 Content of Public Cert instead of DataPower Crypto Objects

### ISSUE THREAD

**Issue by kshkhana** [ibm-apiconnect/policy#4]
Hi,

As I understand the JWS Sign/Verify policy is only for DataPower Crypto Objects, what if we DONT want to store the public certificate in Datapower but retrieve them from an external repository where all the certificates will be stored (to keep it in a central location).

Is it possible to extend the function used here to be using the Base64 content of the certificate instead of the DataPower Crypto object?

**Comment by thomas-burke** [comment]
Hi kshkhana, 
Yes. The policies you refer to use the DataPower jose module. 
https://www.ibm.com/support/knowledgecenter/en/SS9H2Y_7.7.0/com.ibm.dp.doc/jose_js.html

The jose module is flexible. For example, the `jws-sign` policy uses createJWSHeader() ( documented here: https://www.ibm.com/support/knowledgecenter/en/SS9H2Y_7.7.0/com.ibm.dp.doc/jose_js.html#jose.createJWSHeader) 

Note that you probably need to decode the B64 certificate to a raw format before passing it to the jose module.
